### ISSUE TITLE
Attributes context checks - problematic when using "type" attribute with <button>

### ISSUE THREAD

**Issue by jonscottclark** [kizu/bemto#45] opened 2015-11-06 22:16 UTC
Hey kizu,

I'm creating an element with `+e('button')` but I need it to be `type='reset'`. Unfortunately, at the top of **bemto** there's an ["Attributes context checks" area](https://github.com/kizu/bemto/blob/master/bemto.jade#L26-L34) which forces the element to be an `<input>` if there's a `type` attribute. `<button>`s can also have `type='button'` or `type='submit'`, both of which are also valid attribute values for `<input>` elements, so maybe these checks (or just the one for the `type` attribute) should be removed (because they seem very prescriptive). I'll leave it to you, wanted to let you know the situation I ran into :)

**Comment by kizu** [comment] 2015-11-09 10:18
This is a duplicate of #43, and the issue is already fixed in rc-1.0 branch (would be released later this month). Thanks for the report anyway!

**Closed by kizu** 2015-11-09 10:18 UTC

**Comment by jonscottclark** [comment] 2015-11-10 14:48
Oops, so sorry that I did not see it. Thanks again for your hard work on this, looking forward to rc-1.0 :) I will be using it on a large project so I will surely help to test it over the next few months :+1:
