### ISSUE TITLE
How add custom class to element without block prefix?

### ISSUE THREAD

**Issue by rsukochev-ideas** [kizu/bemto#79] opened 2016-04-10 16:48 UTC
```
+b.item
  +e.class1.class2
```

in result:
```
.b-item
  .b-item__class1.b-class2
```

but how get:
```
.b-item
  .b-item__class1.class2
```

**Comment by kizu** [comment] 2016-04-27 09:05
Duplicate of #77, but thanks for the report anyway!

**Closed by kizu** 2016-04-27 09:05 UTC
